const API_INFO_URL = 'https://dogapi.dog/api/v2';
const API_IMG_URL = 'https://dog.ceo/api/breed';

export const API_BREED_LIST_URL = `${API_INFO_URL}/breeds`;
export const apiBreedInfoUrl = (id: string) => `${API_INFO_URL}/breeds/${id}`;
export const API_FACTS_URL = `${API_INFO_URL}/facts?limit=1`;

export const apiBreedImgUrl = (name: string) => {
    name = name.trim();
    let nameUriParts = '';
    if (API_IMG_MAPPING.has(name)) {
        nameUriParts = API_IMG_MAPPING.get(name) as string;
    } else {
        nameUriParts = name.trim()
            .toLocaleLowerCase()
            .split(' ')
            .filter(part => part !== 'american')
            .toReversed()
            .join('/');
    }
    return `${API_IMG_URL}/${nameUriParts}/images/random`;
}

export const getLocalImgUrl = (name: string) => {
    if (LOCAL_IMG_MAPPING.has(name)) {
        return LOCAL_IMG_MAPPING.get(name);
    }
    return null;
}

const API_IMG_MAPPING = new Map<string, string>([
    ["Airedale Terrier", "airedale"],
    ["Alaskan Malamute", "malamute"],
    ["American Eskimo Dog", "eskimo"],
    ["Australian Kelpie", "kelpie"],
    ["Belgian Malinois", "malinois"],
    ["Belgian Tervuren", "tervuren"],
    ["Bernese Mountain Dog", "mountain/bernese"],
    ["Bouvier des Flandres", "bouvier"],
    ["Bullmastiff", "mastiff/bull"],
    ["Bull Terrier", "bullterrier/staffordshire"],
    ["Cardigan Welsh Corgi", "corgi/cardigan"],
    ["Caucasian Shepherd Dog", "ovcharka/caucasian"],
    ["Chinese Shar-Pei", "sharpei"],
    ["Chow Chow", "chow"],
    ["Clumber Spaniel", "clumber"],
    ["Dandie Dinmont Terrier", "terrier/dandie"],
    ["Doberman Pinscher", "doberman"],
    ["English Cocker Spaniel", "spaniel/cocker"],
    ["English Springer Spaniel", "springer/english"],
    ["Entlebucher Mountain Dog", "entlebucher"],
    ["Finnish Lapphund", "finnish/lapphund"],
    ["German Longhaired Pointer", "pointer/germanlonghair"],
    ["German Shepherd Dog", "germanshepherd"],
    ["Greater Swiss Mountain Dog", "mountain/swiss"],
    ["Great Pyrenees", "pyrenees"],
    ["Irish Water Spaniel", "spaniel/irish"],
    ["Japanese Akitainu", "akita"],
    ["Kerry Blue Dog", "terrier/kerryblue"],
    ["Labrador Retriever", "labrador"],
    ["Leonberger", "leonberg"],
    ["Lhasa Apso", "lhasa"],
    ["Manchester Terrier (Toy)", "terrier/toy"],
    ["Old English Sheepdog", "sheepdog/english"],
    ["Parson Russell Terrier", "terrier/russell"],
    ["Pekingese", "pekinese"],
    ["Pembroke Welsh Corgi", "pembroke"],
    ["Poodle (Miniature)", "poodle/miniature"],
    ["Poodle (Standard)", "poodle/standard"],
    ["Poodle (Toy)", "poodle/toy"],
    ["Redbone Coonhound", "redbone"],
    ["Segugio Italiano", "segugio/italian"],
    ["Shiba Inu", "shiba"],
    ["Shih Tzu", "shihtzu"],
    ["Siberian Husky", "husky"],
    ["Smooth Fox Terrier", "terrier/fox"],
    ["Soft Coated Wheaten Terrier", "terrier/wheaten"],
    ["Poodle (Miniature)", "poodle/miniature"],
    ["Spanish Water Dog", "waterdog/spanish"],
    ["Wirehaired Vizsla", "vizsla"],
    ["Working Kelpie", "kelpie"],
]);

const LOCAL_IMG_MAPPING = new Map<string, any>([
    ["Alaskan Klee Kai", "https://upload.wikimedia.org/wikipedia/commons/5/54/WOWAKK-Kukai-Alaskan-Klee-Kai.jpg"],
    ["American English Coonhound", "https://georgiapuppiesfromheaven.com/dog-breed-photos/ameengco.jpg"],
    ["American Foxhound", "https://www.karusek.com.pl/poradnik/wp-content/uploads/sites/3/2021/09/shutterstock_1939375954.jpg"],
    ["American Hairless Terrier","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSk4ySSvBDU2585xRg7Tykty9avSfhN8NIKV92fED_uFYnKHCSMWeqi0EV1d2FY3JIFwwkpBMIQLths3w0P78NWsg"],
    ["American Leopard Hound","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSlEb2Vy_LR28MDTMAFO5z5Cwd7y9MFmxKOTGM7MUHJd1LweSAAPBTv12iS4n_2k3HjoEPPQeeRP18NpYCxtc1a2g"],
    ["American Staffordshire Terrier","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSxzuW0uYebuApU_vk3wdADC1Uge5F42C1_Uss-fPMDo5n_BRT-Tp20jcTS4x5b2a21ZHohBARZPSY8B1nH1es5Tw"],
    ["American Water Spaniel","https://content.osgnetworks.tv/gundog/content/photos/American_water_spaniel_breed-1-840.jpg"],
    ["Anatolian Shepherd Dog","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGva_CC1rdeleoxjxpbNSfvzyYkz-HRqGh8we1iQr9BmFwhDeO0KWJ3A_4jFOnXILnNr9mh7QuGSQhUA0TRtHItw"],
    ["Appenzeller Sennenhund","https://www.zooplus.ch/magazin/wp-content/uploads/2018/09/AdobeStock_11176163.jpg"],
    ["Australian Cattle Dog","https://epieski.pl/wp-content/uploads/2024/07/australian-cattle-dog-1024x805.jpg.webp"],
    ["Australian Shepherd","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSKhe18mz_0MfS7qIY_BbfheWFxi1sTYcCzh5q0UOLgNF9CffYWtWPmQN7w9PWT-Zenmf3kPxbT-B4D7Z108BAr5Q"],
    ["Australian Stumpy Tail Cattle Dog","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaeLkwWiarsKvCcCNZXee4tAVxKK57T5GdDQ&s"],
    ["Azawakh","https://epieski.pl/wp-content/uploads/2024/06/azawakh-1024x856.jpg.webp"],
    ["Barbado da Terceira","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRTqA96VNPDT3xkleKUUG9hMs94s7t6DOA5m-7TUE_58N8XU1WFvchjnikceRYpGWntEvn_QVRIE87w5A7VvDWycg"],
    ["Barbet","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQdLo_E8GwndMpbyvb2-W5LPS7gs4lhojfkefY4ZSJunyOFz03Im1dO6MX4NclmkUczaPDWLpbu-bAdUqpUYc1ltw"],
    ["Basset Fauve de Bretagne","https://www.akc.org/wp-content/uploads/2017/11/AdobeStock_23183632.jpg"],
    ["Bavarian Mountain Scent Houn","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNJ_xb-vQ4pV5mjApoTE9B9KaWnuzbHRVWzU-JFSdrMOJNYq5FmB2CCAzO_ghIp6wANtIbd6kGrpalxvTz6QlciA"],
    ["Bearded Collie","https://zooart.com.pl/blog/wp-content/uploads/2022/07/FOTO-BEARDED-COLLIE-SYLWETKA-1000x667-1.jpg"],
    ["Beauceron","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR58VNjmd6yiBVEXkRXUQ0qaThxfyizC-aGylDTpLiYUsOSNxXo8qvqqYefsyu6ydP2mwrYdiFRf6gt-9yi4lJP0w"],
    ["Belgian Laekenois","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRjWq_GhFbj2X0kXqoG9YO9TVmc6J-q7_mqQ&s"],
    ["Belgian Sheepdog","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt04a_295qKJlnGTdweeHhVW__gb5_Fc4Ot-qD6X3RYgPalshAnixbn8tP5qjiY_nn_HotEqKZ46voiNgLCOndTQ"],
    ["Bergamasco Sheepdog","https://www.dogpackapp.com/blog/wp-content/uploads/2024/10/bergamasco-sheepdog-field.webp"],
    ["Berger Picard","https://www.akc.org/wp-content/uploads/2017/11/Berger-Picard-standing-in-a-field.jpg"],
    ["Biewer Terrier","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT8ueEjVHpkLS-8CaDxcisaW6F8oDF2qkVmF-umNtZT9NCGY9sOKsDln_k3unfpv-30Fz9cwKj0MdrenpzcnF292g"],
    ["Black and Tan Coonhound","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqFa8duJclNYz6LIirpeVl7BFPBqWeS29sHw&s"],
    ["Black Russian Terrier","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrPJxWcjdJTfO2CD38qsI2s-PlIYuOpgG0EQ&s"],
    ["Bloodhound","https://zooart.com.pl/blog/wp-content/uploads/2022/09/BLOODHOUND-1000X667.jpg"],
    ["Bluetick Coonhound","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSfaYz996oBKoIgZilHhlB-t_gAviYp3UXl4o5bHtKrc5n1QbWe-LaCf6IossjQ_VYVUvnf9Fyj-OgJSzif2nSpXg"],
    ["Boerboel","https://pl.petglobals.com/imagesaver/iblockdefault/big/fpyjhzhigproh3csxury_1587381588.jpg"],
    ["Bohemian Shepherd","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqfANNtJl-YZg2tkoQtzhqNCfNgjpu1zFOe7KspjCesJTeMEaEvqFjg59tlzqx7G1sLpDiyeZOXiLv78U7hqcRqQ"],
    ["Bolognese","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTJ6780vOIApaP0Jp4tgxPEyfQLiYxgpyc1St3o4T4p5CXuXj2ij1eu-hjdo1RbAgprcnztHFty4wfeQYnqn1irUG0cVzOEbET9AtixBXQ"],
    ["Boston Terrier","https://upload.wikimedia.org/wikipedia/commons/6/66/BostonTerrierBrindleStand_w.jpg"],
    ["Boykin Spaniel","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQBQEsDRuui9QO4i3sBdY7x17sHW5NTDU0OY85nfeD3raUjUNRb3PdFfg5GvYkkWaIQppyIvzXWpUKoXuu_83s8SQ"],
    ["Bracco Italiano","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTX3S08m4miicgajDvCBkMtT5gbMwnP4QlWr7uRqXyuW_5hZgNIE1l_shB7-0SWD42cx9iJFT8L0pznINGk3lHcnQ"],
    ["Braque du Bourbonnais","https://cdn.wamiz.fr/cdn-cgi/image/format=auto,quality=80,width=532,height=532,fit=cover/animal/breed/pictures/6166e0be9d455686311921.jpg"],
    ["Braque Francais Pyrenean","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTi0Pz26fIXxUJEyIDpV-wsoLFQGThJkciQ_W09D54Mfm-9avbGHAgdpPqAgpFG4r0VFwWFtmXoCIH3SheZJSnqxAIIBEMld5k_VyZQj4E"],
    ["Brittany","https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-07/Brittany1_0.jpg?h=05901361&itok=xAAkqufT"],
    ["Broholmer","https://upload.wikimedia.org/wikipedia/commons/0/0c/Ivarr03.JPG"],
    ["Brussels Griffon","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSnxqwpvyCgCtDqT3EQLEB0BcgbdbdaiY5q3PEqrJDJyJ53t8x3YYz29a6rh6Vj30LPRv2xEn-RJgcYR7fnjFH7tQ"],
    ["Canaan Dog","https://upload.wikimedia.org/wikipedia/commons/8/88/CanaanDog3.jpg"],
    ["Cane Corso","https://upload.wikimedia.org/wikipedia/commons/b/bc/Cane_corso_temi_1_1024x768x24.png"],
    ["Carolina Dog","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRpUmAm23EOTSVIBckzxqlVpfR_RMvzCMZkLH4mKBPliFZyyuC3l_b12Ry4-qAk5ex_Gzi_Ewm1V5eZ5Xh8gbbRng"],
    ["Catahoula Leopard Dog","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREp1tv3W6jRsGvN5UbYPFrAbHWw-H7p3vkE8OcqSQJ2GiSoX7nyhahGv2qXztpEIE4fdTetZj3y76lXU91e0T1mw"],
    ["Cavalier King Charles Spaniel","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaEA3RQqDaTwSZBjaLdiU9hVjQOV7yJVTiS8RlJDmJwUpukTV0cauUuJWLsTxnDiQnW5XJBHsyU0KQ62BNL-3lqg"],
    ["Central Asian Shepherd Dog","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRfyNizPkg9GlvfzIIcKQ5Qg6QI_QK1gUwfmAcLcUQtQb9MZLKuUquCBdCqQ55NGE75QBFOIBqIJLdJsIpMRKoTXw"],
    ["Cesky Terrier","https://cdn.pixabay.com/photo/2013/07/11/19/44/cesky-terrier-144741_960_720.jpg"],
    ["Chesapeake Bay Retriever","https://pet-health-content-media.chewy.com/wp-content/uploads/2024/09/11162036/202107GettyImages-661221626-scaled-1.jpg"],
    ["Chinese Crested","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSzv98N8tVAbeaApgASgXQ_615KSD3MbFH1fHCs06qcxyHFM-3qUvhNpBSpGdoEv50d63T-MpxPcSMJtLT2MugBbA"],
    ["Chinook","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSn2NvsYoeP0X_8D_i9PrhyWLZX7x7hjNMvkw&s"],
    ["Cirneco dell'Etna","https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Cirneco_dell_Etna_611.jpg/640px-Cirneco_dell_Etna_611.jpg"],
    ["Coton de Tulear","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGrTnOxR1YaQoPgV8009cw1evfdr9J4hcgBZ8oZ8Aqm-YhaD4DB0o6GLV40kcRdzFI4KojYQfPDegVFJ5h1TwE3A"],
    ["Croatian Sheepdog","https://breed-assets.wisdompanel.com/dog/croatian-shepherd-dog/Croatian_Shepherd_Dog_1.jpg"],
    ["Curly-Coated Retriever","https://www.zooplus.pl/magazyn/wp-content/uploads/2022/03/Curly-Coated-Retriever-brazowy.jpg"],
    ["Czechoslovakian Vlcak","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjniKO9Ba06kGEnd8MicPeoWzhBfpNHhtZ5g&s"],
    ["Danish-Swedish Farmdog","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTXBWirw0dW5oKDpuFn1d6fkPuXNmk5H-CNVrLo9DobJt2sZnFlUAFXvDANRvxmd0EXDnyusQnJjSRWQiGHx0G5bQ"],
    ["Deutscher Wachtelhund","https://upload.wikimedia.org/wikipedia/commons/1/1b/Deutscher_Wachtel_2.jpg"],
    ["Dogo Argentino","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRbwet0sTaolwyqaBfeZPYMa4znQMze7NYyAz-8ifeKM4xorx7Dwb-qCXFdU8xg8WT-HUmOLF5ZekbNACDlNsLwSg"],
    ["Dogue de Bordeaux","https://www.zooplus.pl/magazyn/wp-content/uploads/2022/10/dog-z-bordeaux-na-lace-768x512.jpg"],
    ["Drentsche Patrijshond","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTEqBAYdZCZDO92KghBwyfOwI1q2MiGJK0ZNLlXjMpRj6xCmYA8QUZo6kt_f-euixuSZmAhwpfAxe2v57XnFEAfKA"],
    ["Drever","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSXA6pFQ27OSxn-Xi03yOMZhjf_8E_nXPEE5H4YmRN6VvkuTwN03ZAL3Urw-NoGhqR4LxsqDTtMrOEl5M0jl6OZ3A"],
    ["Dutch Shepherd","https://zaklinaczkapsow.pl/wp-content/uploads/2024/03/dutch-shepherd-charakterystyka-i-opis-rasy.jpg"],
    ["English Foxhound","https://www.dailypaws.com/thmb/RH2ALva2q3GOVmx0jE2Ryr-ZLeY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/english-foxhound-standing-in-grass-tongue-out-369157684-2000-a1ae402c2dd141469b22f107564f213c.jpg"],
    ["English Toy Spaniel","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR7eXVQwRCw_xustCDrMV7ehQZxshYo7frrHJ2pAlXfsdQRCAYYZ4UALWCHMV-zLOeD4_24QWtfkzwCbKu6-f5AYw"],
    ["Estrela Mountain Dog","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6Q55Zvmea8pIbj2N2bE4fMfRYnbDcgjmQVaYsPmup6G6_Mgjuk37y4FPeCLExzGmsStFKpX2Q1OPmd6c-8LAreg"],
    ["Eurasier","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBlgbeSEUB8LYRHvc8hreNX33o6wiL1qkPoZcVjchv63QnBK67-zSDPHILAxwxaileCMqUyMns7-rg0b5KJ13txQ"],
    ["Field Spaniel","https://zooart.com.pl/blog/wp-content/uploads/2025/01/shutterstock_1671161980.jpg"],
    ["Finnish Spitz","https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-07/Finnish%20Spitz1.jpg?h=bcb3ed5f&itok=vZJKDmqe"],
    ["Flat-Coated Retriever","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ1ylKNWLkfHry5gemcN9VVNYXdyLiIh5aemEixD3rB5S1gNy4Ulu1_7Sx-4MbiiS3-gGkwpIEVsDnwsQPOBdJkFg"],
    ["French Spaniel","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgLxKqo2u37uilgTFTFB8sjd3B8nMeWEBmwtIHx6GOjGCt3qF4dMoF2iM2HGx6SzKCBKTm4G5vhOmsnrar8xQJGLqKvXMcdZHyvxxqhhY"],
    ["German Pinscher","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQjWWu5fsY0OrVTLA6h4e7HbnRvBUvfoW3FzOjgpWBZvW3sFCROgMlJslS9ZKtqt6_-kadvSKaQ_EoMmKdE00HVMw"],
    ["German Shorthaired Pointer","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcShnZWKi_Pm3lcoApmQMAzaetzG4YP48n1QIfBbQ3pQ-d_5g6OCQlzvfSIPiYHyBG-ciiaf2vViN1Bae_ISzIfscA"],
    ["German Spitz","https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-07/German%20Spitz%20%28Klein%291.jpg?h=508350a0&itok=D9Hp42He"],
    ["German Wirehaired Pointer","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ8YTEjv3SsacoWOt8B3jHPBqhNc8TbTvNNjFkShjT8ZldW5N6DUMOANZfCmy2ynpqfgMLDv2PIO13_bci1K7cBBg"],
    ["Glen of Imaal Terrier","https://petkarma.pl/media/articles/99678/1_thumb_99678.jpg"],
    ["Grand Basset Griffon Vendéed","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQsFRayTPPSj50dSOWLzJQnuREjjn-WFTrIZGobF9ULEZtbERV66lfqXxbQldhIBR5rJsBpuCWUpuJC_gGlMt8TVQ"],
    ["Hamiltonstovare","https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-07/Hamiltonstovare1.jpg?h=a8c0966a&itok=VLkU4mQ4"],
    ["Hanoverian Scenthound","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTbuiBKLEctE3SLG53Lr5Uf0XpppFHGuJYrt4Iwl7S-0L3uBb18nt9q0VYRhvAHvpFxVoYGvXYQyMCIDgTK4MiXWg"],
    ["Harrier","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQVsUL8J9c9mHhmK6x3U3AQTpPy4fag3I44zEPg89l89lj9h9eRL2lwQOPABFKfK6MMmCgZsqsIli86mM971MZZPTf9TRkftMYmzRV00w"],
    ["Hokkaido","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR9100QE8oLMrUeQ_TgyL5Iwj7sKo-a6ONnO-MbSPPeLQ9MCuUzzmzsW701E2kByfqvfPI1dinDBHNFZGxZRGxr7A"],
    ["Hovawart","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9-BsAEkmYJCy2bLaBV-hls78hIKxi7Fyw0WFWLW5Epi7Q6J6Dr53pnklv12xf2Qujjjeznkhl7w2yFICy633KZQ"],
    ["Icelandic Sheepdog","https://www.akc.org/wp-content/uploads/2017/11/Icelandic-Sitting.jpg"],
    ["Irish Red and White Setter","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ2vksD8sdLRU-QeVyyRDHw51EtaFDmdY0VRnNWYD2E49lO_lfQ2FDNitpSQrwX6rKT3fX2rZvO__F6uOrGGwgHPw"],
    ["Jagdterrier","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSpbQLL1KrrArCdxEQVn1rXgDjbqyBnPzP3l_G_AkPQB8ERyQldWUasewmezVdHLS4sdfSsGVBsv9i-NkGLRxVSBQ"],
    ["Japanese Chin","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR-OmwuCm3F_6P1R0nt3wwIRmIsEq8AHdYECzSb_5gxmTInUhoLFuNxCGOjQ04-V48JEW-i8J8X-FjQsb2v72AQqg"],
    ["Japanese Terrier","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeTuP2NMSySHNE7Qn0f2jEycgdGgfEFu8zGYKLhPW1G0C0hYQUyhJ3oQGrNTfrSDe67P-hHdALLahjtUbdTxTyzA"],
    ["Jindo","https://sklepzkarmami.pl/poradnik/wp-content/uploads/2024/05/Korean-Jindo-Dog2-scaled.jpg"],
    ["Kai Ken","https://cdn.wamiz.fr/cdn-cgi/image/format=auto,quality=80,width=1200,height=675,fit=cover/animal/breed/dog/adult/66952fa108b49255447042.jpg"],
    ["Karelian Bear Dog","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTjKnPq-dyICd6tL94rnUGUrJfkxI9wX-gClmIeQy_AY_3xF-htJy-e5fu9BkhXSR66oPqb-iBlcqpEWZALwzHRoQ"],
    ["Kerry Blue Terrier","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR4-SETdtOunNwd8JKYg-mssdVUAXNfDmRYuOPjXyZuaPBWpUphFt5GUwyvQwKuF0_VAbixFQSSSumoxdp4-DrQAA"],
    ["Kishu Ken","https://i.pinimg.com/736x/95/9d/e2/959de200a2f071535bd170898ee5ec20.jpg"],
    ["Kromfohrlander","https://www.zooplus.pl/magazyn/wp-content/uploads/2021/11/Kromfohrlander.jpg"],
    ["Lagotto Romagnolo","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTO-4lSySIj0wbq60jKgAz753R1lnxUduTxBwd1Kkx1ZF_JSfzEU-6tfiRAx0V94xEzD4xoeR2NV0-Rm2AR-KX_dw"],
    ["Lancashire Heeler","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRijhBdFWH0PE1kweJiba6znxPl79H12WOQk9ykhk4tG3dtlyQiW1X4gmZPYx79hY7dU4I9q-uXDWILs49OmAkKng"],
    ["Lapponian Herder","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRl2swbHj8_V-rgOGbbHLov6nWyryjtsD_HM6Dgr0M8vvHG7kJSJLKEElx_1L9lbvRu5Bn2fGCtUdsX0M59UQUjTw"],
    ["Löwchen","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSMQ3M_uFO3qlaWpro6ucZHQyavdgvqpiJ-mFn4CbTf0EvXGP4lAjFgmij8ZCErxgLY-gCZr3YQSWaH3nhPJHqJnA"],
    ["Manchester Terrier (Standard)","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSu_XUxp4OVpBoiG9H5LBAyuGBjHerlq5_gyiSEZt0G52_rMi3eRO4z6GboJSO_DSKJGCmIk33BfoSdPbHpbt__Vg"],
    ["Miniature American Shepherd","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQykNFu1ptcfMnfWn8HpTC48yc7lHSxB4rklWPAai6dwdnyUTfxQWK0d1tol2rKAMIz0-EFqCV6lMtxn4uq2qBSNg"],
    ["Miniature Bull Terrier","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3EQvRZFYBhapgelS75sCh_F5qNAqf2h3vi_iDqZQouiLeg1pW2skQsWv5p4jDABt625MRrbdF5O11l2dwy64F2Q"],
    ["Mountain Cur","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRO9ZjPOIhBn8bssmaS8kiXTL2jmV4N6yujTA-Ti4_sViBzbLsC97AmCjgKJHLB_u6mgpAzGGtHU_Q1JiK64YK0XqmUJt7ReqZwHaaq7kc"],
    ["Mudi","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcR9nd1jqSJvTCUtfUICkZszQXS19uc_0GYspNS2HQNjiGXsM_cRHeiqVoAvceCAlEn4HPkYGwEFFJHk5rz6P8bYrA"],
    ["Neapolitan Mastiff","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEnmWN4tkBA4WcdxTKrGx-4VUni7rRNTyu6N0itj1UbMZg81_-gFoAqDPXU76E36Y8C_U&usqp=CAU"],
    ["Nederlandse Kooikerhondje","https://upload.wikimedia.org/wikipedia/commons/f/f0/Kooiker03.jpg"],
    ["Norrbottenspets","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7oU1gVEJMVhagyB4jmSMfMMVAcK2Z7ZUOwBIktNcd45_MYcYMxtKG8WwepU4od1gyynA&usqp=CAU"],
    ["Norwegian Lundehund","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvlgV8lC95ZxGtCUUaZtwqh0q7x9K7ZWnrV06ea6anisuN2clCCRWqozQYoBYz9yu64rTj2ZQETbXY7uCVoqKUCzfRRc-phw-xTEeXrA"],
    ["Nova Scotia Duck Tolling Retriever","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQe0-FamaZdDIjInvkwoY_tPj9aFEQ-paFNoonNZauEIEUjG9oehojTeS4i2V50vvmjH6OsYBlJLR7DAuSf5jXSAYSkvNaDBC4j-yrD4g"],
    ["Perro de Presa Canario","https://adiestrar-perros.com/wp-content/uploads/2024/12/presa-canario-en-la-nieve.jpeg"],
    ["Peruvian Inca Orchid","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ90UGP4Oq-7aOGyWIwxkX93ApCccpFbph7kGCR5VMSZWMh0EDloatP_4oCcnNsPQQyBjCdqtTlS6cFBp3---K1sQ"],
    ["Petit Basset Griffon Vendéen","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9ADgvbZvvLv39E8-H5LXgSMdVwEgSU_vZjbq2R7yADjMu_HH61PlpfSkdVWV8LPle_w5HRScc94oFwxgPzzG8lg"],
    ["Pharaoh Hound","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQQvgRrwq2Z8BMuH5H4QbUimq2s7H9kxJIQ10nt9aH2D4wIDqhAehYQqWqqBIaHZPE8SPJP3thEW4QORkKo5ozbbg"],
    ["Plott","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaaP3M7tEFwNFRoYK6NuOkqG-auUgytDXAmnMjaYR-8GMzuHF7spk4UDBSbOj6l86UgyktcgbCtuRwG22TLiz3ow"],
    ["Polish Lowland Sheepdog","https://cdn.butternutbox.com/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzlaQ0E9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c3459f2b3665411c3f16312e7143d530fb4d40f1/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBPZ2wzWldKd09oSnlaWE5wZW1WZmRHOWZabWwwV3dkcEFyQUVhUUpZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--b8ee90cfb113b226e9fc6ead29dc293e599be6e5/1.png"],
    ["Porcelaine","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlOF6bZD5EhYNDhO0ZJegTKq644JtPbtuNzoMNh3HMC3OzfGTwn7cG_LEXOkFmKxkr57RzSbqLdUl_tlX9REIxyg"],
    ["Portuguese Podengo","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSrgYnMv-YlMT9T4B6iBtpw5xFhg_p7Kna5U36NzmFYldywVbpanG3jdwk8WJgf5mCmgcuURxqmQEs2uvj_GR4Z0w"],
    ["Portuguese Podengo Pequeno","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0FA7AQbnA5EphSBwvapME520aWlCMJpiO9w&s"],
    ["Portuguese Pointer","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTDf0ReBWtInNTl6XSE08wtXWO-llj_JuYM5WApccxfGzsjJi2F4_tuHg3IKY7mEi6RFMRVHnrklHpUVAZ1USRzzA"],
    ["Portuguese Sheepdog","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRymIgaff_ZrO3NvxUL1lKS-NBXmqaMNi5BMgr2ML3kmMXmyIp60rF-8o86hk57p7ZJWa1SjGCDoIsk3Gt74dgu3g"],
    ["Portuguese Water Dog","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQpXpSjiLvOn2suxJmfCfr45D5vhO_1aef36JAR_BfMTqo74PaWqK7z77y1tmYiIExShvwjIDgUQO8y_1F88kJG0A"],
    ["Pudelpointer","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcR_ioubObCzjgdan-WnhOVzNLlk_a7QqC_240KbWbFhZDKE6J1Z9LziwaSOau-Y6TV4-AxcjSxGhjzv_n6h4eZckQ"],
    ["Puli","https://www.zooplus.pl/magazyn/wp-content/uploads/2025/03/Puli.jpeg"],
    ["Pumi","https://www.zooplus.pl/magazyn/wp-content/uploads/2025/03/Pumi.jpeg"],
    ["Pyrenean Mastiff","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcT47P1JNST0AURfOwlPy_t7dpkfpmizGX4lbaNqqwAPSkFIakFQHr3QquBPKbwZvfAzRbmtWIwc0USNSKqYyXLpzw"],
    ["Pyrenean Shepherd","https://www.akc.org/wp-content/uploads/2017/11/Pyrenean-Shepherd-standing-in-profile-in-a-field.jpg"],
    ["Rafeiro do Alentejo","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSOM44xw05A_9blspCB2GNzlIjYkdLXizim_ZbTp_tIk3-2eRG-tubiWHTAbvB6GBimOeXKrv_COm1V_p6Kdg8piw"],
    ["Rat Terrier","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRPR-neV5Uy6Vwux_aT3AucqH7fMet4JIvmnyeWG3B48OLMkPjCpyuyW7Pr3v-5DrzeV_eehbekf9YqVzLb4IQTdg"],
    ["Romanian Carpathian Shepherd","https://upload.wikimedia.org/wikipedia/commons/4/41/Carpatin.jpg"],
    ["Romanian Mioritic Shepherd Dog","https://cdn-fastly.petguide.com/media/2022/02/16/8240851/romanian-mioritic-shepherd-dog.jpg?size=720x845&nocrop=1"],
    ["Russian Toy","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQkfaDv7h-pi1qymz1n9ulfZpwp6ct9SkktDHPQpKvaXAuQ9SLOnWVKo6qvM7BgtCqeOoKpHoUdgZZLLugCYVJrIA"],
    ["Russian Tsvetnaya Bolonka","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGvKada4wS-m32rVwubMgRYHSWK7zROUziNcET-p7EbuX8OIZGN-CtA9eHNnwM2HNfbXAWnJfu5LwFYWLlwr5MIw"],
    ["Saint Bernard","https://cdn.butternutbox.com/rails/active_storage/representations/proxy/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNS8wQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9025209af3e49ad675038b11fa5f47d66a7cfc5f/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaDdCem9MWm05eWJXRjBPZ2wzWldKd09oSnlaWE5wZW1WZmRHOWZabWwwV3dkcEFyQUVhUUpZQWc9PSIsImV4cCI6bnVsbCwicHVyIjoidmFyaWF0aW9uIn19--b8ee90cfb113b226e9fc6ead29dc293e599be6e5/1440x580_Bernardyn-1.png"],
    ["Schapendoes","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTQ6_r9yMD_UNXA9FKDgmpWinbRE47KzoKxUeBCP69GcrWdIbFVZCpWpZ9cMcVpBl5zbpmk19cC3ISXVD4nAodwcw"],
    ["Shikoku","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIlOfdb-Sogpar0fjFrrksFMg7vtnJnnH1nw&s"],
    ["Skye Terrier","https://upload.wikimedia.org/wikipedia/commons/6/61/Skye_terrier_800.jpg"],
    ["Sloughi","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTVfeHKy7LsJ0lGxii9SOsATdqt2FCYTvAE5Z1UMEb-Gx0QIPykFrOna0Q8rkNnbP9U2nrTxRu54mT6NBVDW5V6KQ"],
    ["Slovakian Wirehaired Pointer","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRiLjEN_1rdSX4RfW5bXvP3_8yMqiZnSccrSBKTTkTDucGg_XfP-9GaeYYMk6mVcDsiS4KdU9g8nlK-qZXXTNw0SA"],
    ["Slovensky Cuvac","https://www.zoohit.sk/magazin/wp-content/uploads/2022/11/slovensky-cuvac.jpg"],
    ["Slovensky Kopov","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRffXB1Frw3VGl4z84ssTfArVtX88GVGRSJUI0Dj6XTRFKPkdZxxODSfk8piJYq29XSyQ&usqp=CAU"],
    ["Small Munsterlander","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBXJEevXr7WxGvEP-Syp2LWPWqh_kL8Cr_fkWarklG3bm80Io8I7CwqAdL3LE8Md9lqSIrCXxBZpZPP0l4YDMYg"],
    ["Spanish Mastiff","https://www.akc.org/wp-content/uploads/2017/11/Spanish-Mastiff.jpg"],
    ["Spinone Italiano","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQd_9wGwwzhpTSIjB8gZpU_uF4cbLnfNWfKStxG2hUFSBUAaHn30VmBGaYV9vGp-LNK19NUcmm6BEsiTIf2vuZvKA"],
    ["Stabyhoun","https://zpsiegopunktuwidzenia.pl/wp-content/uploads/2019/12/Wyzel-fryzyjski-stabyhoun-cena-charakter-rasa-psa-blog-o-psach.jpg"],
    ["Staffordshire Bull Terrier","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz3Y2Z82A0iSEWs_DrnTs1qc_jF0XP5tYewv4zF411qRumEhw0dWNkIFoN8-nrZsLOJ_n2VZ6wBaPEhoz7IHaJ3Q"],
    ["Standard Schnauzer","https://www.akc.org/wp-content/uploads/2017/11/Standard-Schnauzer-standing-outdoors.jpg"],
    ["Swedish Lapphund","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRMfGWTh8v3B-8rLbfwVbgMEZuO5jg_XvGPuzwKlmmCHA_nahoVY0DHqu5NzRdvajxMFTa4mN1HgrS26LHgvuYjNA"],
    ["Swedish Vallhund","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcT-_1t5m7Eh8F2VvbKY4_HqTH7Q2mpmIZ0RT9t4aduuau6H75dHbKXj-dBt3yx_dS_KADZHZJEpHlubCvSeUu0oMw"],
    ["Taiwan Dog","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtK0EdWHLKiv0v3GiZ753c3WZUE5x94FL0YR2J8kTWTMI86PPW2uQ9bZdQKoZRCPCgRnoVh5TbCnmRzFeu9VA0tA"],
    ["Teddy Roosevelt Terrier","https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/14142750/Teddy-Roosevelt-Terrier-running-in-FastCAT.jpg"],
    ["Thai Ridgeback","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1DnxMix8DfdyqCPZFggaIT9kpDfBKNb98pbO4Slo6oofKI33nbeKd4EePjwYU8vLP978VEaLvdrDtBfjPcY_1mQ"],
    ["Tibetan Spaniel","https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-08/Tibetan%20Spaniel1.jpg?h=58b1a78b&itok=UMLabUVy"],
    ["Tornjak","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnyAp6lk3PCpAS2qcGmYImfs6WEpptrT3Jocpj7Yxb8NJMyqO79kOSUlREru5hdrsU6ieymRZjUzK5i4t9vaVNZw"],
    ["Tosa","https://www.akc.org/wp-content/uploads/2017/11/Tosa-on-White-01.jpg"],
    ["Toy Fox Terrier","https://upload.wikimedia.org/wikipedia/commons/2/24/Toy_Fox_Terrier_2.jpg"],
    ["Transylvanian Hound","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRrDXeB-YbkqVCaDKhvy5VoqALxc1WyO5teGma4WeVeh1XjvKkPHyk3Lzx2KJ1-awXitd25C-1T3sASD2ATvkE62RthjGNmHZGFhl1JPw"],
    ["Treeing Tennessee Brindle","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTC1-5nknj_FlQ8or_V0-zklMKyRXbU5LAvJ1885fTxWVqoVsWoYhDt_tWwSR1_oAVPsU0dubblhDaIHu1WMsMe8Q"],
    ["Treeing Walker Coonhound","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQd40RZ1kqtNWfhKDw4xL7rb4rxWNNC3h0JIJmiPo8abb7J0OoQg8YO2ZOs_itWReYCcdXcxtjUIiQU2tbswJAKUg"],
    ["Volpino Italiano","https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGbt9GVQtAvluzHp2B15DCCnuFkCbnK6BJ8ICg7Z_sKfj-S_j6yIP38s1KfxlQph1VfnkgqxqRbKKa5cibTkerUw"],
    ["Welsh Springer Spaniel","https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-08/Spaniel%20%28Welsh%20Springer%291.jpg?h=7b8a5764&itok=mD3pLXRk"],
    ["West Highland White Terrier","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcSgd3NS9jAygE4VORyejJe2vVM-PCWm1vfDC4FZ-AyhuZPmKj-NBwcawL07hSHHyEdDHO6djq1vZ3dJdsD2zL0xmg"],
    ["Wetterhoun","https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTn5c1WZHFZQHAU04v6pAPK48Qfyq3sVdUFbYnWuOjfc9WvuN7j5dLYT3WDiWbZGqhgQ7a3Uueibf3wDO4adiOLhQ"],
    ["Wire Fox Terrier","https://www.purina.co.uk/sites/default/files/styles/square_medium_440x440/public/2022-07/Fox%20Terrier%20Wire%20Coat2.jpg?h=0f5e4270&itok=ZXZ8as7s"],
    ["Wirehaired Pointing Griffon","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTJKmKxXcA2ZPT5hSRmvas7jUm4p_rNUbqtCtVA1PtOGU_hVev0elRYa5iAXMxT3Dnv1Y2FljOQZ_gzqbMW1JrONg"],
    ["Xoloitzcuintli","https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS_0PXqUyWYQBZm8a29FA8k49Hduy8Xp18k5hPN3czD3Qge_0-F8y8iS8ijrQ78lZYUnEuyOeN418VKyu1aCs5rjWm2F6vpPW4C8siiNw"],
    ["Yakutian Laika","https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTIju9rtsvCBlypmwkGFbusCIJLqldGbnMa13sypPt6GbJf8PYhC7cF8sIV66vQYLNeBhtIjdn6XEnyQwntF5VyWA"]
]);
